// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njmzznceiykpybpuabgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qbXp6bmNlaXlrcHlicHVhYmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODI0ODgsImV4cCI6MjA2NzU1ODQ4OH0.SqeHr41yIXqdkxG4jMOTE8u4Yb3nxseujgEg22csj5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});